// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAPcHGETbsB1DYGExkgZZAtbatTvAVFQM4',
    appId: '1:131532027644:web:e7f9dc7f2af940df274979',
    messagingSenderId: '131532027644',
    projectId: 'social-medial-applicatio-70c85',
    authDomain: 'social-medial-applicatio-70c85.firebaseapp.com',
    storageBucket: 'social-medial-applicatio-70c85.appspot.com',
    measurementId: 'G-0K18VK5WC7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0DwhkHuGZweJ-sQBQBs9kvU2u1ilJnAM',
    appId: '1:131532027644:android:df24a926e47cfd57274979',
    messagingSenderId: '131532027644',
    projectId: 'social-medial-applicatio-70c85',
    storageBucket: 'social-medial-applicatio-70c85.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBcpkI1KY9h8oZr68J2dw4KU4UsIDylcpc',
    appId: '1:131532027644:ios:dc78ae27fb31d7d7274979',
    messagingSenderId: '131532027644',
    projectId: 'social-medial-applicatio-70c85',
    storageBucket: 'social-medial-applicatio-70c85.appspot.com',
    iosBundleId: 'com.example.socialMediaApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBcpkI1KY9h8oZr68J2dw4KU4UsIDylcpc',
    appId: '1:131532027644:ios:0f8155cce0746fc7274979',
    messagingSenderId: '131532027644',
    projectId: 'social-medial-applicatio-70c85',
    storageBucket: 'social-medial-applicatio-70c85.appspot.com',
    iosBundleId: 'com.example.socialMediaApplication.RunnerTests',
  );
}
